name: Deployment-CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile
      
  Security-check-Trivy:
    runs-on: self-hosted
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Installing Trivy
      run: |
          sudo apt-get install wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy   
    - run: trivy --version
    - name: Running Trivy Scan
      run: trivy fs --scanners vuln --offline-scan --format table -o trivy-report.txt .
    - run: cat trivy-report.txt
    
    - name: Upload Trivy report
      uses: actions/upload-artifact@v4
      with:
         name: trivy-report
         path: trivy-report.txt

      
  Code-check-gitleaks:
    runs-on: self-hosted
    needs: Security-check-Trivy
    steps:
    - uses: actions/checkout@v4
    - name: Installing gitleaks
      run: sudo apt install gitleaks
    - name: Code scan using git leaks
      run: gitleaks detect source .

  test:
    runs-on: self-hosted
    needs: Code-check-gitleaks
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit Test Cases
      run: mvn test
  
  Build-and-Sonarcube-scan:
    runs-on: self-hosted
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: build
      run: mvn package
    - name: Upload JAR artifact 
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar 
    - uses: actions/checkout@v6
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v8.2.0 # Ex: v4.1.0, or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  Build-docker-image:
    runs-on: self-hosted
    needs: Build-and-Sonarcube-scan
    steps:
    - uses: actions/checkout@v4
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: app  # this will download JAR to ./app folder
        
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
          context: .
          push: true
          tags: sa2000/myapp:latest  
          file: ./Dockerfile

  Image-scan-trivy:
    runs-on: self-hosted
    steps:
      - name: Scan Docker Hub Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: sa2000/myapp:latest
          format: table
          vuln-type: os
          scanners: vuln

          
